// Preliminary Business Studies concept & term library
// Definitions written in NESA marking-guideline style, mapped to the same
// topic / sub-area keys used by SYLLABUS in syllabus.js so results feed the
// topic analysis. Fields: id, term, topic, sub, def, eg?
const GLOSSARY = [

// ================= NATURE OF BUSINESS =================
// --- Role of business ---
{id:"nb-business", term:"Business", topic:"Nature of Business", sub:"Role of business", def:"An organisation engaged in the production and/or exchange of goods and/or services to satisfy the needs of society, typically to earn a profit."},
{id:"nb-goods", term:"Goods", topic:"Nature of Business", sub:"Role of business", def:"Tangible, physical products that can be seen and touched, such as a car or a loaf of bread."},
{id:"nb-services", term:"Services", topic:"Nature of Business", sub:"Role of business", def:"Intangible products that cannot be touched, such as advice, entertainment or transport."},
{id:"nb-profit", term:"Profit", topic:"Nature of Business", sub:"Role of business", def:"The financial reward for taking risk in business; the surplus remaining after all costs have been deducted from revenue."},
{id:"nb-risk", term:"Risk", topic:"Nature of Business", sub:"Role of business", def:"The chance of financial loss associated with a business decision, balanced against the potential reward."},
{id:"nb-entrepreneurship", term:"Entrepreneurship", topic:"Nature of Business", sub:"Role of business", def:"The ability to identify a business opportunity and organise the resources necessary to exploit it, accepting the associated risk."},
{id:"nb-innovation", term:"Innovation", topic:"Nature of Business", sub:"Role of business", def:"The introduction of new products, processes or ideas that add value for customers or improve business performance."},
{id:"nb-wealth", term:"Wealth", topic:"Nature of Business", sub:"Role of business", def:"The accumulation of assets and resources of value created through business activity, contributing to a society's standard of living."},
{id:"nb-quality-of-life", term:"Quality of life", topic:"Nature of Business", sub:"Role of business", def:"The overall wellbeing of individuals and communities, which businesses influence through employment, incomes, goods, services and innovation."},
{id:"nb-employment", term:"Employment", topic:"Nature of Business", sub:"Role of business", def:"Work provided by businesses that generates wages and salaries for individuals, a key role of business in society."},

// --- Types of businesses ---
{id:"nb-sme", term:"Small to medium enterprise (SME)", topic:"Nature of Business", sub:"Types of businesses", def:"A business classified by size, generally employing fewer than 200 people, often independently owned and operated with limited market share."},
{id:"nb-large-business", term:"Large business", topic:"Nature of Business", sub:"Types of businesses", def:"A business employing 200 or more people, typically with significant market share, more resources and more complex management structures than an SME."},
{id:"nb-local-business", term:"Local business", topic:"Nature of Business", sub:"Types of businesses", def:"A business classified by scope that operates within a single town, suburb or region."},
{id:"nb-national-business", term:"National business", topic:"Nature of Business", sub:"Types of businesses", def:"A business classified by scope that operates across an entire country."},
{id:"nb-global-business", term:"Global business", topic:"Nature of Business", sub:"Types of businesses", def:"A business classified by scope that operates in more than one country, also called a multinational or transnational corporation."},
{id:"nb-primary-industry", term:"Primary industry", topic:"Nature of Business", sub:"Types of businesses", def:"Businesses that extract or harvest raw materials directly from nature, such as farming, fishing and mining."},
{id:"nb-secondary-industry", term:"Secondary industry", topic:"Nature of Business", sub:"Types of businesses", def:"Businesses that manufacture or process raw materials into finished or semi-finished goods, such as construction and manufacturing."},
{id:"nb-tertiary-industry", term:"Tertiary industry", topic:"Nature of Business", sub:"Types of businesses", def:"Businesses that provide services to consumers and other businesses, such as retail, health, education and finance.", eg:"Health services are part of the tertiary sector."},
{id:"nb-quaternary-industry", term:"Quaternary industry", topic:"Nature of Business", sub:"Types of businesses", def:"Businesses providing information-based and intellectual services, such as information technology, research and consultancy."},
{id:"nb-quinary-industry", term:"Quinary industry", topic:"Nature of Business", sub:"Types of businesses", def:"Businesses providing services that were traditionally unpaid, such as childcare, care for the elderly and domestic work now provided commercially."},
{id:"nb-sole-trader", term:"Sole trader", topic:"Nature of Business", sub:"Types of businesses", def:"A business owned and operated by one person, who has unlimited liability for the business's debts and keeps all profits."},
{id:"nb-partnership", term:"Partnership", topic:"Nature of Business", sub:"Types of businesses", def:"A business owned by two to twenty people who share the profits, losses and unlimited liability of the business, usually governed by a partnership agreement."},
{id:"nb-private-company", term:"Private company", topic:"Nature of Business", sub:"Types of businesses", def:"A company (denoted 'Pty Ltd') with limited liability whose shares are not offered to the general public and are held by a small group of shareholders."},
{id:"nb-public-company", term:"Public company", topic:"Nature of Business", sub:"Types of businesses", def:"A company (denoted 'Ltd') with limited liability whose shares are listed and traded on the stock exchange and can be bought by the public."},
{id:"nb-govt-enterprise", term:"Government enterprise", topic:"Nature of Business", sub:"Types of businesses", def:"A business owned and operated by the government to provide goods or services, often in areas the private sector would under-supply."},
{id:"nb-unlimited-liability", term:"Unlimited liability", topic:"Nature of Business", sub:"Types of businesses", def:"A legal condition, applying to sole traders and partnerships, where the owner's personal assets can be used to pay business debts."},
{id:"nb-limited-liability", term:"Limited liability", topic:"Nature of Business", sub:"Types of businesses", def:"A legal condition, applying to companies, where shareholders' liability for business debts is limited to the amount they invested."},

// --- Influences in the business environment ---
{id:"nb-external-influence", term:"External influences", topic:"Nature of Business", sub:"Influences in the business environment", def:"Factors outside a business's direct control that affect its operations, including economic, financial, geographic, social, legal, political, institutional, technological and competitive factors."},
{id:"nb-internal-influence", term:"Internal influences", topic:"Nature of Business", sub:"Influences in the business environment", def:"Factors within a business's control that affect its operations, including its products, location, resources, management and business culture."},
{id:"nb-stakeholders", term:"Stakeholders", topic:"Nature of Business", sub:"Influences in the business environment", def:"Individuals or groups with an interest in a business's operations and performance, including owners, employees, customers, suppliers, government and the community."},
{id:"nb-zoning", term:"Zoning", topic:"Nature of Business", sub:"Influences in the business environment", def:"Local government regulation that restricts how land in a particular area may be used, e.g. residential, commercial or industrial.", eg:"Local (council) government is responsible for zoning laws."},
{id:"nb-business-culture", term:"Business culture", topic:"Nature of Business", sub:"Influences in the business environment", def:"The shared values, attitudes and practices that characterise how a business and its employees operate."},
{id:"nb-competitive-situation", term:"Competitive situation", topic:"Nature of Business", sub:"Influences in the business environment", def:"The level and nature of competition a business faces in its market, which shapes its pricing, products and strategy."},
{id:"nb-technological-influence", term:"Technological influence", topic:"Nature of Business", sub:"Influences in the business environment", def:"The effect of new technology on how businesses produce, market and deliver goods and services."},
{id:"nb-economic-influence", term:"Economic influences", topic:"Nature of Business", sub:"Influences in the business environment", def:"External factors such as interest rates, inflation, economic growth and unemployment that affect consumer spending and business costs."},

// --- Business growth and decline ---
{id:"nb-life-cycle", term:"Business life cycle", topic:"Nature of Business", sub:"Business growth and decline", def:"The stages a business passes through over time: establishment, growth, maturity and post-maturity (renewal or decline)."},
{id:"nb-establishment-stage", term:"Establishment stage", topic:"Nature of Business", sub:"Business growth and decline", def:"The first stage of the business life cycle, where the business is set up, seeking to attract customers and become viable."},
{id:"nb-growth-stage", term:"Growth stage", topic:"Nature of Business", sub:"Business growth and decline", def:"The stage of the business life cycle marked by rising sales, growing customer awareness and increasing staff levels, but also cash-flow and management challenges."},
{id:"nb-maturity-stage", term:"Maturity stage", topic:"Nature of Business", sub:"Business growth and decline", def:"The stage of the business life cycle where sales growth slows and the business seeks to consolidate its market position."},
{id:"nb-post-maturity", term:"Post-maturity stage", topic:"Nature of Business", sub:"Business growth and decline", def:"The final stage of the business life cycle, where a business either renews itself (e.g. new products, takeover, merger) or declines towards closure."},
{id:"nb-renewal", term:"Renewal strategies", topic:"Nature of Business", sub:"Business growth and decline", def:"Actions a business takes at post-maturity to remain competitive, such as introducing new products, mergers, takeovers or expanding into new markets."},
{id:"nb-merger", term:"Merger", topic:"Nature of Business", sub:"Business growth and decline", def:"The combination of two businesses into a single new entity, often to achieve growth, cost savings or increased market share."},
{id:"nb-takeover", term:"Takeover", topic:"Nature of Business", sub:"Business growth and decline", def:"The acquisition of one business by another, where the acquiring business gains control."},
{id:"nb-voluntary-cessation", term:"Voluntary cessation", topic:"Nature of Business", sub:"Business growth and decline", def:"The closure of a business by choice of the owner, e.g. retirement or sale, rather than through financial failure."},
{id:"nb-liquidation", term:"Liquidation", topic:"Nature of Business", sub:"Business growth and decline", def:"The involuntary winding-up of a business, where its assets are sold to pay creditors because it can no longer meet its debts."},

// ================= BUSINESS MANAGEMENT =================
// --- Nature of management ---
{id:"bm-management", term:"Management", topic:"Business Management", sub:"Nature of management", def:"The process of coordinating and overseeing the resources and activities of a business to achieve its goals effectively and efficiently."},
{id:"bm-interpersonal-skills", term:"Interpersonal skills", topic:"Business Management", sub:"Nature of management", def:"A manager's ability to build relationships, communicate and work effectively with others."},
{id:"bm-strategic-thinking", term:"Strategic thinking", topic:"Business Management", sub:"Nature of management", def:"A management skill involving the ability to see the big picture, anticipate change and plan for the long-term direction of the business."},
{id:"bm-vision", term:"Vision", topic:"Business Management", sub:"Nature of management", def:"A clear, long-term view of what a business aims to become, guiding its strategy and decisions."},
{id:"bm-decision-making", term:"Decision-making", topic:"Business Management", sub:"Nature of management", def:"The management skill of selecting a course of action from a range of alternatives to solve a problem or achieve a goal."},
{id:"bm-flexibility", term:"Flexibility / adaptability", topic:"Business Management", sub:"Nature of management", def:"A manager's ability to adjust plans and practices in response to changing internal or external circumstances."},
{id:"bm-effective-management", term:"Effective management", topic:"Business Management", sub:"Nature of management", def:"Management that successfully achieves business goals while balancing the sometimes conflicting interests of different stakeholders."},

// --- Achieving business goals ---
{id:"bm-business-goals", term:"Business goals", topic:"Business Management", sub:"Achieving business goals", def:"The targets a business sets to work towards, which may include profit, market share, growth, share price, and social and environmental objectives."},
{id:"bm-market-share", term:"Market share", topic:"Business Management", sub:"Achieving business goals", def:"The percentage of total sales in a market that is captured by a particular business."},
{id:"bm-growth-goal", term:"Growth (as a goal)", topic:"Business Management", sub:"Achieving business goals", def:"A business objective focused on increasing sales, market share, staff numbers or the scale of operations over time."},
{id:"bm-social-goals", term:"Social objectives", topic:"Business Management", sub:"Achieving business goals", def:"Business goals concerned with contributing positively to the community, employees and other stakeholders, beyond pure profit."},
{id:"bm-environmental-goals", term:"Environmental objectives", topic:"Business Management", sub:"Achieving business goals", def:"Business goals focused on minimising negative environmental impact, such as reducing waste, emissions or resource use."},
{id:"bm-staff-motivation", term:"Motivation", topic:"Business Management", sub:"Achieving business goals", def:"The internal drive that encourages employees to work towards business goals, influenced by factors such as recognition, reward and job satisfaction."},
{id:"bm-mentoring", term:"Mentoring", topic:"Business Management", sub:"Achieving business goals", def:"A staff development strategy where an experienced employee guides and supports a less experienced one."},
{id:"bm-training", term:"Training", topic:"Business Management", sub:"Achieving business goals", def:"Activities designed to develop employees' skills and knowledge so they can perform their roles more effectively and contribute to business goals."},

// --- Management approaches ---
{id:"bm-classical-approach", term:"Classical approach to management", topic:"Business Management", sub:"Management approaches", def:"A management approach that views management as planning, organising and controlling, typically within a hierarchical structure and an autocratic leadership style."},
{id:"bm-behavioural-approach", term:"Behavioural approach to management", topic:"Business Management", sub:"Management approaches", def:"A management approach that emphasises leading, motivating and communicating with employees, often using teams and a participative/democratic leadership style."},
{id:"bm-contingency-approach", term:"Contingency approach to management", topic:"Business Management", sub:"Management approaches", def:"A management approach based on adapting management style and strategy to suit changing circumstances, rather than following one fixed method."},
{id:"bm-hierarchical-structure", term:"Hierarchical structure", topic:"Business Management", sub:"Management approaches", def:"An organisational structure with multiple levels of authority, where instructions typically flow from the top down."},
{id:"bm-autocratic-leadership", term:"Autocratic leadership", topic:"Business Management", sub:"Management approaches", def:"A leadership style where the manager makes decisions alone with little input from employees."},
{id:"bm-democratic-leadership", term:"Participative / democratic leadership", topic:"Business Management", sub:"Management approaches", def:"A leadership style where employees are involved in decision-making alongside management."},
{id:"bm-teams", term:"Teams", topic:"Business Management", sub:"Management approaches", def:"Groups of employees working together towards a shared goal, associated with the behavioural approach to management."},

// --- The management process ---
{id:"bm-operations", term:"Operations", topic:"Business Management", sub:"The management process", def:"The business function responsible for producing goods and/or services, including the production process and quality management."},
{id:"bm-production-process", term:"Production process", topic:"Business Management", sub:"The management process", def:"The way inputs (resources) are transformed into outputs (goods and services) by a business."},
{id:"bm-quality-control", term:"Quality control", topic:"Business Management", sub:"The management process", def:"Inspecting products or processes at various points to check for and correct problems and defects."},
{id:"bm-quality-assurance", term:"Quality assurance", topic:"Business Management", sub:"The management process", def:"A system of processes and standards used throughout production to ensure a business consistently achieves a set level of quality."},
{id:"bm-tqm", term:"Total quality management (TQM)", topic:"Business Management", sub:"The management process", def:"An ongoing, business-wide commitment to quality and continuous improvement applied to every aspect of a business's operations."},
{id:"bm-marketing", term:"Marketing", topic:"Business Management", sub:"The management process", def:"The business function responsible for identifying the target market and satisfying customer needs, using the marketing mix."},
{id:"bm-target-market", term:"Target market", topic:"Business Management", sub:"The management process", def:"The specific group of customers a business aims its products and marketing efforts at."},
{id:"bm-marketing-mix", term:"Marketing mix", topic:"Business Management", sub:"The management process", def:"The combination of product, price, place and promotion strategies a business uses to market its goods or services."},
{id:"bm-personal-selling", term:"Personal selling", topic:"Business Management", sub:"The management process", def:"A promotional strategy involving direct, face-to-face communication between a salesperson and a potential customer."},
{id:"bm-sales-promotion", term:"Sales promotion", topic:"Business Management", sub:"The management process", def:"A short-term promotional strategy designed to boost sales, such as free samples, discounts or competitions.", eg:"Giving away free product samples to increase sales is a sales promotion."},
{id:"bm-advertising", term:"Advertising", topic:"Business Management", sub:"The management process", def:"A paid, non-personal form of promotion used to inform or persuade an audience about a product via media such as TV, print or online."},
{id:"bm-publicity", term:"Publicity", topic:"Business Management", sub:"The management process", def:"Unpaid promotion of a business or product generated through media coverage, not directly controlled by the business."},
{id:"bm-finance-function", term:"Finance (business function)", topic:"Business Management", sub:"The management process", def:"The business function responsible for managing money, including preparing the cash flow statement, income statement and balance sheet."},
{id:"bm-cash-flow-statement", term:"Cash flow statement", topic:"Business Management", sub:"The management process", def:"A financial statement showing the cash received and paid by a business over a period, used to monitor liquidity."},
{id:"bm-income-statement", term:"Income statement", topic:"Business Management", sub:"The management process", def:"A financial statement (also called a profit and loss statement) showing a business's revenue, expenses and resulting profit or loss over a period."},
{id:"bm-balance-sheet", term:"Balance sheet", topic:"Business Management", sub:"The management process", def:"A financial statement showing a business's assets, liabilities and owner's equity at a specific point in time.", eg:"Owner's equity = Assets − Liabilities."},
{id:"bm-owners-equity", term:"Owner's equity", topic:"Business Management", sub:"The management process", def:"The owner's claim on the assets of the business after all liabilities have been deducted.", eg:"Owner's equity = Total assets − Total liabilities."},
{id:"bm-gross-profit", term:"Gross profit", topic:"Business Management", sub:"The management process", def:"Sales revenue minus the cost of goods sold, before operating expenses are deducted.", eg:"Gross profit = Sales − Cost of goods sold."},
{id:"bm-cost-of-goods-sold", term:"Cost of goods sold", topic:"Business Management", sub:"The management process", def:"The direct cost of the stock a business has sold during a period.", eg:"Cost of goods sold = Opening stock + Purchases − Closing stock."},
{id:"bm-hr-function", term:"Human resources (business function)", topic:"Business Management", sub:"The management process", def:"The business function responsible for managing employees, including recruitment, training, employment contracts and separation."},
{id:"bm-recruitment", term:"Recruitment", topic:"Business Management", sub:"The management process", def:"The process of attracting, screening and selecting suitable candidates for a job within a business."},
{id:"bm-on-costs", term:"On-costs", topic:"Business Management", sub:"The management process", def:"Costs additional to wages incurred by a business for employing labour, such as superannuation, sick leave and workers' compensation."},
{id:"bm-separation", term:"Separation", topic:"Business Management", sub:"The management process", def:"The ending of an employee's time with a business, which may be voluntary (e.g. resignation, retirement) or involuntary (e.g. redundancy, dismissal)."},
{id:"bm-ethical-behaviour", term:"Ethical business behaviour", topic:"Business Management", sub:"The management process", def:"Conducting business according to accepted moral principles, considering the impact of decisions on all stakeholders."},

// --- Management and change ---
{id:"bm-change-management", term:"Managing change", topic:"Business Management", sub:"Management and change", def:"The process of planning and implementing change within a business in response to internal and external influences."},
{id:"bm-need-for-change", term:"Identifying the need for change", topic:"Business Management", sub:"Management and change", def:"The first step in managing change, recognising that current practices are no longer suited to the business's circumstances."},
{id:"bm-resistance-to-change", term:"Resistance to change", topic:"Business Management", sub:"Management and change", def:"Reluctance or opposition from employees or other stakeholders towards a proposed change in the business."},
{id:"bm-business-info-systems", term:"Business information systems", topic:"Business Management", sub:"Management and change", def:"Systems used to collect, process and communicate information within a business to support decision-making and change."},
{id:"bm-management-consultants", term:"Management consultants", topic:"Business Management", sub:"Management and change", def:"External experts engaged by a business to provide specialist advice, often to help plan and implement change."},
{id:"bm-achievable-goals", term:"Achievable goals", topic:"Business Management", sub:"Management and change", def:"Realistic, attainable targets set during change management so that progress can be measured and staff remain motivated."},

// ================= BUSINESS PLANNING =================
// --- Small to medium enterprises ---
{id:"bp-sme-def", term:"SME (definition)", topic:"Business Planning", sub:"Small to medium enterprises", def:"A business, independently owned and operated, employing fewer than 200 people (often under 20 for 'small'), with limited market share."},
{id:"bp-sme-characteristics", term:"Characteristics of SMEs", topic:"Business Planning", sub:"Small to medium enterprises", def:"Typical features of SMEs include personalised service, local markets, owner-provided capital, and the owner being closely involved in decision-making."},
{id:"bp-sme-economic-role", term:"Economic contribution of SMEs", topic:"Business Planning", sub:"Small to medium enterprises", def:"The role SMEs play in an economy, including employment creation, innovation, contribution to GDP and support for larger businesses through supply chains."},
{id:"bp-sme-failure-factors", term:"Factors contributing to SME failure", topic:"Business Planning", sub:"Small to medium enterprises", def:"Common causes of small business failure, including poor planning, inadequate record-keeping, insufficient capital, poor location and lack of management experience."},
{id:"bp-sme-success-factors", term:"Factors contributing to SME success", topic:"Business Planning", sub:"Small to medium enterprises", def:"Common contributors to small business success, including sound planning, adequate finance, market research and effective management."},

// --- Influences in establishing an SME ---
{id:"bp-personal-qualities", term:"Personal qualities (of an owner)", topic:"Business Planning", sub:"Influences in establishing an SME", def:"Attributes such as qualifications, skills, motivation and entrepreneurship that influence a person's success in establishing a new business."},
{id:"bp-business-idea", term:"The business idea", topic:"Business Planning", sub:"Influences in establishing an SME", def:"The concept for the product or service a new business will offer, which must be assessed against the level of competition it will face."},
{id:"bp-new-business", term:"Establishing a new business", topic:"Business Planning", sub:"Influences in establishing an SME", def:"An establishment option where an entrepreneur starts a business from scratch, offering full control but higher risk and start-up cost."},
{id:"bp-existing-business", term:"Buying an existing business", topic:"Business Planning", sub:"Influences in establishing an SME", def:"An establishment option where an entrepreneur purchases a business that is already operating, gaining an established customer base and systems."},
{id:"bp-franchise", term:"Franchise", topic:"Business Planning", sub:"Influences in establishing an SME", def:"An establishment option where a franchisee pays for the right to operate a business using an established brand, systems and support from the franchisor.", eg:"Franchising reduces risk because the business model is already proven, but the franchisee has less independence."},
{id:"bp-market-considerations", term:"Market considerations", topic:"Business Planning", sub:"Influences in establishing an SME", def:"Factors relating to the good/service, price and location that must be considered when establishing a business."},
{id:"bp-finance-source-cost", term:"Source and cost of finance", topic:"Business Planning", sub:"Influences in establishing an SME", def:"Where a new business obtains its funds (e.g. owner's equity, bank loans) and the cost of using that finance, such as interest."},
{id:"bp-business-name", term:"Business name registration", topic:"Business Planning", sub:"Influences in establishing an SME", def:"A legal requirement to register the name a business trades under, part of the legal aspects of establishing an SME."},
{id:"bp-wage-nonwage-costs", term:"Wage and non-wage costs", topic:"Business Planning", sub:"Influences in establishing an SME", def:"The human resources costs of establishing a business: wages paid to staff, and non-wage costs such as on-costs and training."},
{id:"bp-taxation", term:"Taxation (business establishment)", topic:"Business Planning", sub:"Influences in establishing an SME", def:"Federal and state taxes and local rates/charges that a new business must plan for, such as income tax and GST."},

// --- The business planning process ---
{id:"bp-situational-analysis", term:"Situational analysis", topic:"Business Planning", sub:"The business planning process", def:"An assessment of a business's current position, including its internal strengths/weaknesses and external opportunities/threats, used as a source of planning ideas.", eg:"A SWOT analysis and market analysis are both part of situational analysis."},
{id:"bp-swot", term:"SWOT analysis", topic:"Business Planning", sub:"The business planning process", def:"A planning tool that identifies a business's internal Strengths and Weaknesses and external Opportunities and Threats."},
{id:"bp-vision-goals", term:"Vision, goals and objectives", topic:"Business Planning", sub:"The business planning process", def:"The stage of business planning where a business defines its long-term vision and sets specific goals and objectives to achieve it."},
{id:"bp-organising-resources", term:"Organising resources", topic:"Business Planning", sub:"The business planning process", def:"The stage of business planning that coordinates operations, marketing, finance and human resources to implement the plan."},
{id:"bp-forecasting", term:"Forecasting", topic:"Business Planning", sub:"The business planning process", def:"Predicting future business performance, including total revenue, total costs, break-even point and cash flow projections."},
{id:"bp-total-revenue", term:"Total revenue", topic:"Business Planning", sub:"The business planning process", def:"The total income a business earns from selling its goods or services.", eg:"Total revenue = Price × Quantity sold."},
{id:"bp-break-even", term:"Break-even analysis", topic:"Business Planning", sub:"The business planning process", def:"A forecasting technique that identifies the level of sales at which total revenue equals total costs, so the business makes neither a profit nor a loss."},
{id:"bp-monitoring-evaluation", term:"Monitoring and evaluation", topic:"Business Planning", sub:"The business planning process", def:"Reviewing actual business performance (sales, budgets, profit) against the plan, to identify variances that may require corrective action."},
{id:"bp-corrective-action", term:"Corrective action", topic:"Business Planning", sub:"The business planning process", def:"Changes made by a business in response to monitoring and evaluation, to bring performance back in line with its plan."},
{id:"bp-budget", term:"Budget", topic:"Business Planning", sub:"The business planning process", def:"A financial plan that estimates a business's future income and expenses over a set period, used to monitor performance."},

// --- Critical issues in business success and failure ---
{id:"bp-business-plan-importance", term:"Importance of a business plan", topic:"Business Planning", sub:"Critical issues in business success and failure", def:"A written business plan clarifies direction, helps secure finance, and improves the likelihood of business success by anticipating problems."},
{id:"bp-staffing-teams", term:"Staffing and teams", topic:"Business Planning", sub:"Critical issues in business success and failure", def:"Having the right people, organised effectively into teams, is a critical issue affecting whether a business plan succeeds."},
{id:"bp-trend-analysis", term:"Trend analysis", topic:"Business Planning", sub:"Critical issues in business success and failure", def:"Examining data over time to identify patterns that inform business decisions and planning."},
{id:"bp-competitive-advantage", term:"Competitive advantage", topic:"Business Planning", sub:"Critical issues in business success and failure", def:"An attribute that allows a business to outperform its competitors, such as lower costs, superior quality or a unique product."},
{id:"bp-over-extension", term:"Over-extension of finance", topic:"Business Planning", sub:"Critical issues in business success and failure", def:"A situation where a business takes on more debt or commitments than it can manage, a common cause of business failure."},
{id:"bp-technology-use", term:"Using technology (in planning)", topic:"Business Planning", sub:"Critical issues in business success and failure", def:"Applying technology to improve efficiency, reduce costs or reach customers, an important factor in sustaining business success."},
{id:"bp-economic-conditions", term:"Economic conditions (and business success)", topic:"Business Planning", sub:"Critical issues in business success and failure", def:"The broader state of the economy — such as interest rates, consumer confidence and economic growth — which can significantly affect a business's success or failure."},
{id:"bp-strategic-alliance", term:"Strategic alliance", topic:"Business Planning", sub:"Critical issues in business success and failure", def:"A formal arrangement between two or more businesses to cooperate for mutual benefit, such as sharing resources or entering new markets, while remaining independent.", eg:"An advantage of strategic alliance is cost savings through shared resources."},

];
